window.BOL_WORKSHOPS = [
  {
    id: "workshop-1",
    title: "Cultivating Inner Quiet: A Contemplative Retreat",
    category: "Retreats",
    format: "In-Person",
    date: "Oct 14 – 16, 2026",
    fullDateLine: "Friday, October 14 – Sunday, October 16  •  9:00 AM - 4:00 PM PST",
    startDate: "2026-10-14T09:00:00",
    endDate: "2026-10-16T16:00:00",
    time: "9:00 AM – 4:00 PM PST",
    duration: "3 days (Weekend)",
    attendanceType: "In person",
    facilitator: "Sr. Clare Joseph",
    facilitatorRole: "Contemplative Retreat Director & Spiritual Guide",
    facilitatorBio:
      "Sr. Clare has walked alongside spiritual seekers for over 25 years, guiding silent retreats, monastic hospitality days, and contemplative prayer circles across Northern California.",
    location: "Sacramento Center — Main Sanctuary",
    venueName: "Bread of Life Center — Main Sanctuary",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$150 (Sliding Scale Available)",
    status: "Opened",
    seatsLeft: 4,
    scopes: ["All", "For you", "This weekend"],
    image: "/src/assets/images/nature_meadow_journaling_reflection_1790449443945.jpg",
    excerpt:
      "A weekend dedicated to silence, guided reflection, and restoring spiritual clarity through ancient contemplative practices.",
    overviewLead:
      "Cultivating Inner Quiet is where unhurried stillness meets grounded contemplative practice, inviting you to step away from daily noise and reconnect with interior peace.",
    overviewBody: [
      "Cultivating Inner Quiet is more than a weekend workshop—it is a restorative sanctuary designed for anyone longing to slow down, listen deeply, and tend to the inner life through shared silence, gentle instruction, and meaningful community presence.",
      "Across three unhurried days in our Main Sanctuary and courtyard gardens, Sr. Clare Joseph will guide participants through centering prayer sits, contemplative walking, Lectio Divina, and optional one-on-one spiritual check-ins. Whether you are seasoned in silent retreat or arriving for your very first contemplative gathering, you will leave with a sustainable daily rhythm to carry home."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-2",
    title: "Spiritual Direction Foundations",
    category: "Spiritual Direction",
    format: "Online (Zoom)",
    date: "Nov 2, 2026",
    fullDateLine: "Monday, November 2  •  6:30 PM - 8:00 PM PST",
    startDate: "2026-11-02T18:30:00",
    endDate: "2026-11-02T20:00:00",
    time: "6:30 PM – 8:00 PM PST",
    duration: "1.5 hours",
    attendanceType: "Online (Zoom)",
    facilitator: "David Sterling, M.Div",
    facilitatorRole: "Author & Senior Spiritual Director",
    facilitatorBio:
      "Author and master spiritual director specializing in contemplative listening, discernment accompaniment, and community formation.",
    location: "Virtual Zoom Room",
    venueName: "Bread of Life Virtual Zoom Sanctuary",
    addressLine1: "Online via Zoom (Hosted from 1260 Fulton Avenue, Suite A)",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County (Online)",
    isPhysical: false,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$45",
    status: "Opened",
    seatsLeft: 12,
    scopes: ["All", "For you", "Today"],
    image: "/src/assets/images/nature_sunlit_conversation_veranda_1790449455567.jpg",
    excerpt:
      "Learn the core principles of deep listening and walking alongside others in their personal faith journey.",
    overviewLead:
      "Spiritual Direction Foundations introduces the ancient art of sacred accompaniment—learning how to hold space without fixing, advising, or rushing.",
    overviewBody: [
      "Spiritual Direction Foundations is an interactive evening gathering for people curious about receiving spiritual direction or discerning a call to accompany others in their spiritual lives.",
      "Together with David Sterling, M.Div, we will explore how contemplative listening differs from coaching or counseling, practice small-group sacred listening triads, and reflect on how attention to the Spirit unfolds in ordinary conversation."
    ],
    registrationUrl: "discernment-next-step.html#register"
  },
  {
    id: "workshop-3",
    title: "Weekly Morning Prayer Circle",
    category: "Weekly Groups",
    format: "Hybrid",
    date: "Every Tuesday",
    fullDateLine: "Tuesday, October 6  •  7:00 AM - 8:00 AM PST",
    startDate: "2026-10-06T07:00:00",
    endDate: "2026-10-06T08:00:00",
    time: "7:00 AM – 8:00 AM PST",
    duration: "1 hour",
    attendanceType: "In person & Online (Hybrid)",
    facilitator: "Deacon Marcus Reyes",
    facilitatorRole: "Contemplative Prayer Leader",
    facilitatorBio:
      "Deacon Marcus has led the Tuesday prayer circle since its founding in 2019, drawing on Ignatian and centering-prayer traditions.",
    location: "Sacramento Center Chapel + Zoom",
    venueName: "Bread of Life Center Chapel & Zoom",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "Free",
    status: "Opened",
    seatsLeft: 20,
    scopes: ["All", "For you", "Today"],
    image: "/src/assets/images/nature_garden_circle_listening_1790449431149.jpg",
    excerpt:
      "Begin the week grounded — a quiet half hour of shared scripture and silence, open to newcomers any Tuesday.",
    overviewLead:
      "Weekly Morning Prayer Circle offers a gentle, grounded beginning to your Tuesday through shared silence, brief sacred reading, and warm community companionship.",
    overviewBody: [
      "Weekly Morning Prayer Circle is a welcoming hybrid gathering held simultaneously in our candlelit Sacramento Chapel and on Zoom. No prior experience with contemplative prayer is needed—simply arrive as you are before the busyness of the workday begins.",
      "We open with a brief breath prayer and a short reading from a contemplative poet or scripture, sit together in twenty minutes of quiet stillness, and close with optional gratitude intentions and morning tea for those attending in person."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-4",
    title: "Leading with Presence: A Workshop for Ministry Leaders",
    category: "Leadership",
    format: "In-Person",
    date: "Nov 18, 2026",
    fullDateLine: "Wednesday, November 18  •  10:00 AM - 3:00 PM PST",
    startDate: "2026-11-18T10:00:00",
    endDate: "2026-11-18T15:00:00",
    time: "10:00 AM – 3:00 PM PST",
    duration: "5 hours",
    attendanceType: "In person",
    facilitator: "Rev. Dr. Amara Okonkwo",
    facilitatorRole: "Pastoral Theologian & Leadership Mentor",
    facilitatorBio:
      "Rev. Dr. Okonkwo trains ministry leaders, nonprofit directors, and chaplains across the region in contemplative approaches to pastoral care and sustainable leadership.",
    location: "Sacramento Center — Fellowship Hall",
    venueName: "Bread of Life Center — Fellowship Hall",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$85",
    status: "Opened",
    seatsLeft: 2,
    scopes: ["All", "For you", "This weekend"],
    image: "/src/assets/images/nature_courtyard_table_gathering_1790449477315.jpg",
    excerpt:
      "A day for those who lead others to slow down, reflect on their own formation, and return to their communities renewed.",
    overviewLead:
      "Leading with Presence is where honest reflection meets grounded leadership renewal, created specifically for those who hold space for congregations, teams, and communities.",
    overviewBody: [
      "Leading with Presence is more than a leadership seminar—it is a restorative day of formation dedicated to helping pastors, chaplains, nonprofit leaders, and community organizers lead from an anchored inner life rather than chronic depletion.",
      "Through guided discernment exercises, peer table conversations, unhurried silence, and a shared midday meal at Bread of Life Center, Rev. Dr. Amara Okonkwo invites you to lay down the pressure to perform and rediscover the quiet wellspring that sustains authentic service."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-5",
    title: "Centering Prayer Intensive",
    category: "Retreats",
    format: "In-Person",
    date: "Oct 3, 2026",
    fullDateLine: "Saturday, October 3  •  9:00 AM - 4:00 PM PST",
    startDate: "2026-10-03T09:00:00",
    endDate: "2026-10-03T16:00:00",
    time: "9:00 AM – 4:00 PM PST",
    duration: "7 hours",
    attendanceType: "In person",
    facilitator: "Sr. Clare Joseph",
    facilitatorRole: "Contemplative Retreat Director & Spiritual Guide",
    facilitatorBio:
      "Sr. Clare has walked alongside spiritual seekers for over 25 years, guiding silent retreats and contemplative prayer circles.",
    location: "Sacramento Center — Main Sanctuary",
    venueName: "Bread of Life Center — Main Sanctuary",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$60",
    status: "Full",
    seatsLeft: 0,
    scopes: ["All", "This weekend"],
    image: "/src/assets/images/nature_riverbank_stillness_trees_1790449467034.jpg",
    excerpt:
      "A one-day deep dive into the practice of centering prayer, with extended silence and guided instruction.",
    overviewLead:
      "Centering Prayer Intensive immerses participants in the classic Christian contemplative tradition of consenting to God's presence and action within.",
    overviewBody: [
      "Designed for both beginners seeking a thorough grounding and experienced practitioners wishing to deepen their sit, this full-day intensive alternates brief teaching segments with periods of communal silence and contemplative walking.",
      "Participants will learn how to choose and work gently with a sacred word, navigate interior distraction with compassion, and integrate two daily periods of centering prayer into ordinary household and work life."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-6",
    title: "Advent Reflection Evening",
    category: "Weekly Groups",
    format: "Online (Zoom)",
    date: "Aug 12, 2026",
    fullDateLine: "Wednesday, August 12  •  6:00 PM - 7:30 PM PST",
    startDate: "2026-08-12T18:00:00",
    endDate: "2026-08-12T19:30:00",
    time: "6:00 PM – 7:30 PM PST",
    duration: "1.5 hours",
    attendanceType: "Online (Zoom)",
    facilitator: "Deacon Marcus Reyes",
    facilitatorRole: "Contemplative Prayer Leader",
    facilitatorBio:
      "Deacon Marcus has led contemplative prayer circles since 2019, drawing on Ignatian and centering-prayer traditions.",
    location: "Virtual Zoom Room",
    venueName: "Bread of Life Virtual Zoom Sanctuary",
    addressLine1: "Online via Zoom (Hosted from 1260 Fulton Avenue, Suite A)",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County (Online)",
    isPhysical: false,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "Free",
    status: "Closed",
    seatsLeft: 0,
    scopes: ["All", "Today"],
    image: "/src/assets/images/nature_guided_walk_oaks_1790449419333.jpg",
    excerpt:
      "An evening of shared reflection to open the season together, online.",
    overviewLead:
      "Advent Reflection Evening gathers our wider community online for candlelit stillness, poetry, and contemplative waiting.",
    overviewBody: [
      "In a season often crowded with hurry and obligation, this 90-minute online gathering creates a quiet threshold of sacred pause, music, and guided journaling from the comfort of your own home.",
      "Together we reflect on themes of watchful hope, stillness in the dark, and making room for new life, concluding with small-group blessings for the weeks ahead."
    ],
    registrationUrl: "discernment-next-step.html#register"
  },
  {
    id: "workshop-7",
    title: "Sitting with Grief: A Half-Day Gathering",
    category: "Retreats",
    format: "In-Person",
    date: "Sep 26, 2026",
    fullDateLine: "Saturday, September 26  •  9:00 AM - 1:00 PM PST",
    startDate: "2026-09-26T09:00:00",
    endDate: "2026-09-26T13:00:00",
    time: "9:00 AM – 1:00 PM PST",
    duration: "4 hours",
    attendanceType: "In person",
    facilitator: "Hannah Alvarez, LMFT",
    facilitatorRole: "Spiritual Director & Grief Companion",
    facilitatorBio:
      "Contemplative spiritual director and grief companion who holds space for individuals and groups navigating loss and life transition.",
    location: "Sacramento Center — Quiet Garden Room",
    venueName: "Bread of Life Center — Quiet Garden Room",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$45 (Pay-What-You-Can)",
    status: "Opened",
    seatsLeft: 6,
    scopes: ["All", "For you", "This weekend"],
    image: "/src/assets/images/nature_garden_circle_listening_1790449431149.jpg",
    excerpt:
      "A gentle half day of companionship, guided reflection, and quiet space for people carrying a loss, recent or long held.",
    overviewLead:
      "Sitting with Grief offers a compassionate, unhurried morning where loss does not need to be explained away, fixed, or carried in isolation.",
    overviewBody: [
      "Anyone holding grief they have not had space to sit with—whether a recent bereavement, a relationship transition, or a sorrow carried quietly for years—is welcome in this circle. No particular faith background or prior contemplative experience is expected.",
      "The morning opens with a grounding practice, followed by guided individual reflection, quiet time in the garden, an optional small-group sharing circle, and a simple closing ritual for honoring what is being carried."
    ],
    registrationUrl: "sitting-with-grief.html"
  },
  {
    id: "workshop-8",
    title: "Discernment When the Next Step Is Unclear",
    category: "Spiritual Direction",
    format: "Online (Zoom)",
    date: "Sep 25, 2026",
    fullDateLine: "Friday, September 25  •  7:00 PM - 9:00 PM PST",
    startDate: "2026-09-25T19:00:00",
    endDate: "2026-09-25T21:00:00",
    time: "7:00 PM – 9:00 PM PST",
    duration: "2 hours",
    attendanceType: "Online (Zoom)",
    facilitator: "David Sterling, M.Div",
    facilitatorRole: "Author & Senior Spiritual Director",
    facilitatorBio:
      "Author and master spiritual director specializing in contemplative listening and community formation.",
    location: "Virtual Zoom Room",
    venueName: "Bread of Life Virtual Zoom Sanctuary",
    addressLine1: "Online via Zoom (Hosted from 1260 Fulton Avenue, Suite A)",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County (Online)",
    isPhysical: false,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$35 (Pay-What-You-Can)",
    status: "Opened",
    seatsLeft: 8,
    scopes: ["All", "For you", "Today"],
    image: "/src/assets/images/nature_guided_walk_oaks_1790449419333.jpg",
    excerpt:
      "Grounded contemplative practices for a crossroads or decision you have been carrying for a while without forcing quick answers.",
    overviewLead:
      "Discernment When the Next Step Is Unclear invites you to bring a real life crossroads into a space of patient, wisdom-rooted listening.",
    overviewBody: [
      "When we stand at a vocational, relational, or spiritual threshold, our culture urges us to make pro-and-con lists and rush toward certainty. Contemplative discernment offers a gentler, truer way of noticing where inner freedom and life are drawing us.",
      "In this two-hour interactive session, David Sterling guides participants through Ignatian consolation/desolation awareness, somatic listening, and quiet journaling so you can listen for the next faithful step without pressure."
    ],
    registrationUrl: "discernment-next-step.html"
  },
  {
    id: "workshop-9",
    title: "Listen to Your Life: Autumn Cohort",
    category: "Weekly Groups",
    format: "In-Person",
    date: "Oct 8, 2026",
    fullDateLine: "Thursday, October 8  •  6:00 PM - 8:00 PM PST",
    startDate: "2026-10-08T18:00:00",
    endDate: "2026-10-08T20:00:00",
    time: "6:00 PM – 8:00 PM PST",
    duration: "2 hours (6-Week Series)",
    attendanceType: "In person",
    facilitator: "Elena Rostova, MA",
    facilitatorRole: "Small-Group Facilitator & Spiritual Director",
    facilitatorBio:
      "Small-group facilitator and spiritual director guiding seasonal cohorts in narrative reflection and sacred listening.",
    location: "Sacramento Center — Library Room",
    venueName: "Bread of Life Center — Library Room",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$120 (6-Week Series)",
    status: "Opened",
    seatsLeft: 5,
    scopes: ["All", "For you"],
    image: "/src/assets/images/nature_courtyard_table_gathering_1790449477315.jpg",
    excerpt:
      "Six weeks in a small, facilitated circle exploring your personal story, life transitions, and shared sacred presence.",
    overviewLead:
      "Listen to Your Life: Autumn Cohort is an intimate six-week circle dedicated to honoring your lived story as a primary place where the sacred speaks.",
    overviewBody: [
      "Limited to ten participants in our warm Library Room, this seasonal cohort weaves together Parker Palmer's Courage & Renewal practices, reflective writing prompts, and clear group agreements that protect every person's autonomy and silence.",
      "Each Thursday evening offers a quiet harbor to look back at the chapters that shaped you, attend to the season you are in now, and be witnessed by a trustworthy circle of peers."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-10",
    title: "A Season of Letting Go",
    category: "Retreats",
    format: "In-Person",
    date: "Nov 8, 2026",
    fullDateLine: "Sunday, November 8  •  9:00 AM - 12:30 PM PST",
    startDate: "2026-11-08T09:00:00",
    endDate: "2026-11-08T12:30:00",
    time: "9:00 AM – 12:30 PM PST",
    duration: "3.5 hours",
    attendanceType: "In person",
    facilitator: "Sr. Clare Joseph",
    facilitatorRole: "Contemplative Retreat Director & Spiritual Guide",
    facilitatorBio:
      "Sr. Clare has walked alongside spiritual seekers for over 25 years, guiding silent retreats and contemplative prayer circles.",
    location: "Sacramento Center — Main Sanctuary",
    venueName: "Bread of Life Center — Main Sanctuary",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$50 (Sliding Scale Available)",
    status: "Opened",
    seatsLeft: 9,
    scopes: ["All", "This weekend"],
    image: "/src/assets/images/nature_riverbank_stillness_trees_1790449467034.jpg",
    excerpt:
      "A morning workshop on release and unburdening, for whatever season of life is asking you to set something down.",
    overviewLead:
      "A Season of Letting Go draws on the wisdom of autumn to help you name and gently release roles, expectations, or burdens that have run their course.",
    overviewBody: [
      "Just as trees release their leaves to conserve life for the winter ahead, our spiritual lives periodically invite us into purposeful unburdening. Yet letting go—of an old identity, an unspoken resentment, or an exhausting pace—rarely happens by willpower alone.",
      "Through guided contemplation, poetry, outdoor reflection, and a tactile ritual of release, Sr. Clare Joseph creates a peaceful space to honor what has been and open your hands to what comes next."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-11",
    title: "Contemplative Prayer for Beginners",
    category: "Spiritual Direction",
    format: "Hybrid",
    date: "Nov 21, 2026",
    fullDateLine: "Saturday, November 21  •  6:30 PM - 8:30 PM PST",
    startDate: "2026-11-21T18:30:00",
    endDate: "2026-11-21T20:30:00",
    time: "6:30 PM – 8:30 PM PST",
    duration: "2 hours",
    attendanceType: "In person & Online (Hybrid)",
    facilitator: "Deacon Marcus Reyes",
    facilitatorRole: "Contemplative Prayer Leader",
    facilitatorBio:
      "Deacon Marcus has led contemplative prayer circles since 2019, welcoming newcomers to quiet sitting and sacred reading.",
    location: "Sacramento Center Chapel + Zoom",
    venueName: "Bread of Life Center Chapel & Zoom",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$25 (Pay-What-You-Can)",
    status: "Opened",
    seatsLeft: 14,
    scopes: ["All", "For you", "This weekend"],
    image: "/src/assets/images/nature_meadow_journaling_reflection_1790449443945.jpg",
    excerpt:
      "Two unhurried hours on sitting quietly with attention and openness. No prior contemplative background assumed.",
    overviewLead:
      "Contemplative Prayer for Beginners demystifies silent prayer with practical, down-to-earth guidance for anyone who feels their mind is 'too busy' to sit in stillness.",
    overviewBody: [
      "Many people long for quiet prayer yet feel intimidated by silence or unsure what to do when thoughts race. This warm, accessible workshop welcomes complete beginners with zero jargon and plenty of encouragement.",
      "We will explore three classic gateways into stillness—breath prayer, the Examen of ordinary life, and short centering sits—with space for honest questions and practical tips for building a ten-minute daily rhythm."
    ],
    registrationUrl: "discernment-next-step.html#register"
  },
  {
    id: "workshop-12",
    title: "Rhythms of Rest for Caregivers & Helpers",
    category: "Leadership",
    format: "In-Person",
    date: "Oct 24, 2026",
    fullDateLine: "Saturday, October 24  •  10:00 AM - 2:00 PM PST",
    startDate: "2026-10-24T10:00:00",
    endDate: "2026-10-24T14:00:00",
    time: "10:00 AM – 2:00 PM PST",
    duration: "4 hours",
    attendanceType: "In person",
    facilitator: "Rev. Dr. Amara Okonkwo",
    facilitatorRole: "Pastoral Theologian & Leadership Mentor",
    facilitatorBio:
      "Rev. Dr. Okonkwo trains ministry leaders, educators, and caregivers in contemplative resilience and sustainable care.",
    location: "Sacramento Center — Fellowship Hall",
    venueName: "Bread of Life Center — Fellowship Hall",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$65",
    status: "Full",
    seatsLeft: 0,
    scopes: ["All", "This weekend"],
    image: "/src/assets/images/nature_sunlit_conversation_veranda_1790449455567.jpg",
    excerpt:
      "Restorative practices and honest conversation for those who spend their weeks holding space for others in healthcare, education, or ministry.",
    overviewLead:
      "Rhythms of Rest for Caregivers & Helpers is a sanctuary day where those who care for everyone else are invited to be cared for, nourished, and restored.",
    overviewBody: [
      "Whether you care for an aging parent, teach in a classroom, serve in healthcare, or accompany people in crisis, compassion fatigue is real. This four-hour gathering offers a guilt-free pause from being the strong one.",
      "Featuring embodied rest practices, gentle soulful conversation, and a nourishing hot lunch prepared for you, Rev. Dr. Amara Okonkwo guides participants in crafting realistic micro-sabbaths that fit inside demanding caregiving lives."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  },
  {
    id: "workshop-13",
    title: "Lectio Divina & Sacred Listening Circle",
    category: "Weekly Groups",
    format: "Online (Zoom)",
    date: "Every Thursday",
    fullDateLine: "Thursday, October 1  •  12:00 PM - 1:00 PM PST",
    startDate: "2026-10-01T12:00:00",
    endDate: "2026-10-01T13:00:00",
    time: "12:00 PM – 1:00 PM PST",
    duration: "1 hour",
    attendanceType: "Online (Zoom)",
    facilitator: "Elena Rostova, MA",
    facilitatorRole: "Small-Group Facilitator & Spiritual Director",
    facilitatorBio:
      "Small-group facilitator and spiritual director guiding seasonal cohorts in narrative reflection and sacred listening.",
    location: "Virtual Zoom Room",
    venueName: "Bread of Life Virtual Zoom Sanctuary",
    addressLine1: "Online via Zoom (Hosted from 1260 Fulton Avenue, Suite A)",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County (Online)",
    isPhysical: false,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "Free",
    status: "Opened",
    seatsLeft: 18,
    scopes: ["All", "Today"],
    image: "/src/assets/images/nature_garden_circle_listening_1790449431149.jpg",
    excerpt:
      "Pause at midday for ancient slow reading of poetry and scripture, followed by quiet reflection and gentle group sharing.",
    overviewLead:
      "Lectio Divina & Sacred Listening Circle turns your Thursday lunch hour into a refreshing oasis of contemplative reading and attentive silence.",
    overviewBody: [
      "Rooted in the ancient monastic practice of Lectio Divina ('divine reading'), we listen to a short passage of sacred text or lyric poetry read aloud three times with spacious silence between each reading.",
      "Instead of studying or analyzing the text, we listen for the single word or image that shimmers for us today, sharing briefly in a respectful, non-judgmental online circle."
    ],
    registrationUrl: "discernment-next-step.html#register"
  },
  {
    id: "workshop-14",
    title: "Embodied Stillness: Walking the Labyrinth",
    category: "Retreats",
    format: "In-Person",
    date: "Sep 19, 2026",
    fullDateLine: "Saturday, September 19  •  9:30 AM - 12:00 PM PST",
    startDate: "2026-09-19T09:30:00",
    endDate: "2026-09-19T12:00:00",
    time: "9:30 AM – 12:00 PM PST",
    duration: "2.5 hours",
    attendanceType: "In person",
    facilitator: "Hannah Alvarez, LMFT",
    facilitatorRole: "Spiritual Director & Grief Companion",
    facilitatorBio:
      "Contemplative spiritual director and grief companion who holds space for individuals and groups navigating loss and life transition.",
    location: "Sacramento Center — Outdoor Courtyard Labyrinth",
    venueName: "Bread of Life Center — Outdoor Courtyard Labyrinth",
    addressLine1: "1260 Fulton Avenue, Suite A",
    cityStateZip: "Sacramento, CA 95825",
    cityRegion: "Sacramento, Sacramento County",
    isPhysical: true,
    mapQuery: "1260 Fulton Avenue, Sacramento, CA 95825",
    cost: "$30",
    status: "Closed",
    seatsLeft: 0,
    scopes: ["All"],
    image: "/src/assets/images/nature_guided_walk_oaks_1790449419333.jpg",
    excerpt:
      "An outdoor morning of walking meditation, breath prayer, and unhurried stillness along our stone courtyard labyrinth.",
    overviewLead:
      "Embodied Stillness: Walking the Labyrinth invites those who pray best in motion to experience the ancient threefold path of release, receiving, and return.",
    overviewBody: [
      "Unlike a maze designed to make you lose your way, a labyrinth has a single winding path that leads reliably to the center and back out again. Walking it slowly becomes a living metaphor for the spiritual journey.",
      "Under the shade of our courtyard oaks, Hannah Alvarez introduces the history and rhythm of labyrinth prayer before guiding an unhurried morning walk accompanied by acoustic chimes, journaling time, and herbal tea."
    ],
    registrationUrl: "sitting-with-grief.html#register"
  }
];
